apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    type: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      type: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        type: frontend
    spec:
      containers:
        - name: asian-food-container
          image: cheulong/{{ .Values.appName}}:{{ .Values.imageTag }}
          ports:
            - containerPort: 80