apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
    type: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30001